services:
  app:
    build: .
    container_name: "app"
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - ./src:/app/src
      - ./test:/app/test
    networks:
      - library

  postgres:
    image: postgres:16
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - library

volumes:
  postgres_data:

networks:
  library:
    driver: bridge
